name: math_test
version: 0.2.1
author: Kay-Uwe Kirstein
description: A simple web-based math test application
dependencies:
  angular: any
  browser: any
  web_components: any
transformers:
- angular
